# set( $JASYPT_ENCRYPTOR_PASSWORD = 'JASYPT_ENCRYPTOR_PASSWORD:default-password' )
#file: noinspection SpringBootApplicationYaml
spring:
  profiles:
    active: dev

# LINUX
# export JASYPT_ENCRYPTOR_PASSWORD=course-push-secret-key
# java -jar course-push-app.jar
# WINDOWS
# set JASYPT_ENCRYPTOR_PASSWORD=course-push-secret-key
# java -jar course-push-app.jar


jasonlat:
  ecc:
    # 是否启用ECC功能
    enabled: true

    # ECC密钥配置（请替换为您的实际密钥）
    privateKey:
    publicKeyX:
    publicKeyY:

    # 用户上下文缓存配置
    user-context-cache:
      cache-max-size: 5000        # 最大缓存用户数量
      cache-expire-minutes: 120   # 缓存过期时间（分钟）

    # 重放攻击防护缓存配置
    replay-attack:
      cache:
        cache-max-size: 1000      # 最大缓存请求数量
        cache-expire-minutes: 30  # 缓存过期时间（分钟）

    # 唯一请求防护缓存配置
    unique-request:
      cache:
        maximum-size: 10000             # 最大缓存请求数量
        expire-minutes-after-write: 60  # 写入后过期时间（分钟）





