version: '3.8'

services:
  # 应用服务（生产环境）
  ecc-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ecc-server-prod
    restart: unless-stopped
    user: "0:0"  # 以root用户启动，让entrypoint脚本处理权限
    environment:
      # Spring配置
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8089
      
      # Jasypt加密密码（生产环境应该通过外部配置传入）
      JASYPT_ENCRYPTOR_PASSWORD: ${JASYPT_ENCRYPTOR_PASSWORD:-lijiaqiang1024@wt1314520}
      
      # JVM参数（生产环境可以调整更大的内存）
      JAVA_OPTS: "-Xms1g -Xmx2g -XX:+UseG1GC -XX:+PrintGCDetails -XX:+PrintGCTimeStamps"
    ports:
      - "8089:8089"
    volumes:
      - ../data/log:/app/data/log
      - /etc/localtime:/etc/localtime:ro  # 同步时区
    networks:
      - ecc-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8089/api/v1/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G

networks:
  ecc-network:
    driver: bridge